//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RereDaisha
{
    [Serializable]
    public class BallPositionMsg : Message
    {
        public const string k_RosMessageName = "rere_daisha_msgs/BallPosition";
        public override string RosMessageName => k_RosMessageName;

        public int class_id;
        public Geometry.PointMsg position;

        public BallPositionMsg()
        {
            this.class_id = 0;
            this.position = new Geometry.PointMsg();
        }

        public BallPositionMsg(int class_id, Geometry.PointMsg position)
        {
            this.class_id = class_id;
            this.position = position;
        }

        public static BallPositionMsg Deserialize(MessageDeserializer deserializer) => new BallPositionMsg(deserializer);

        private BallPositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.class_id);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.class_id);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "BallPositionMsg: " +
            "\nclass_id: " + class_id.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
