//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RereDaisha
{
    [Serializable]
    public class BallPositionArrayMsg : Message
    {
        public const string k_RosMessageName = "rere_daisha_msgs/BallPositionArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public BallPositionMsg[] balls;

        public BallPositionArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.balls = new BallPositionMsg[0];
        }

        public BallPositionArrayMsg(Std.HeaderMsg header, BallPositionMsg[] balls)
        {
            this.header = header;
            this.balls = balls;
        }

        public static BallPositionArrayMsg Deserialize(MessageDeserializer deserializer) => new BallPositionArrayMsg(deserializer);

        private BallPositionArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.balls, BallPositionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.balls);
            serializer.Write(this.balls);
        }

        public override string ToString()
        {
            return "BallPositionArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nballs: " + System.String.Join(", ", balls.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
